
drop table if exists atn_all_corrupt;
create table atn_all_corrupt (
    id                  serial         primary key,
    deployid            integer              null,
    ptt                 integer              null,
    instr               varchar(8)           null,
    date                varchar(32)          null,
    duplicates          integer              null,
    satellite           varchar(8)           null,
    locationquality     varchar(4)           null,
    latitude            double precision     null,
    longitude           double precision     null,
    reason              varchar(32)          null,
    possible_timestamp  varchar(32)          null,
    possible_type       varchar(32)          null,
    byte_00             integer              null,
    byte_01             integer              null,
    byte_02             integer              null,
    byte_03             integer              null,
    byte_04             integer              null,
    byte_05             integer              null,
    byte_06             integer              null,
    byte_07             integer              null,
    byte_08             integer              null,
    byte_09             integer              null,
    byte_10             integer              null,
    byte_11             integer              null,
    byte_12             integer              null,
    byte_13             integer              null,
    byte_14             integer              null,
    byte_15             integer              null,
    byte_16             integer              null,
    byte_17             integer              null,
    byte_18             integer              null,
    byte_19             integer              null,
    byte_20             integer              null,
    byte_21             integer              null,
    byte_22             integer              null,
    byte_23             integer              null,
    byte_24             integer              null,
    byte_25             integer              null,
    byte_26             integer              null,
    byte_27             integer              null,
    byte_28             integer              null,
    byte_29             integer              null,
    byte_30             integer              null,
    byte_31             integer              null
);

DeployID,Ptt   ,Instr,Date                ,Duplicates,Satellite,LocationQuality,Latitude,Longitude,Reason        ,Possible Timestamp  ,Possible Type,Byte 0,Byte 1,Byte 2,Byte 3,Byte 4,Byte 5,Byte 6,Byte 7,Byte 8,Byte 9,Byte 10,Byte 11,Byte 12,Byte 13,Byte 14,Byte 15,Byte 16,Byte 17,Byte 18,Byte 19,Byte 20,Byte 21,Byte 22,Byte 23,Byte 24,Byte 25,Byte 26,Byte 27,Byte 28,Byte 29,Byte 30,Byte 31
8       ,171361,Mk10 ,23:49:42 19-Jul-2017,          ,         ,3              ,28.3989 ,-80.8063 ,CRC 6599.47960,22:15:00 19-Jul-2016,Fast-GPS     ,113   ,156   ,113   ,231   ,100   ,240   ,24    ,185   ,60    ,133   ,56     ,42     ,50     ,27     ,25     ,166    ,248    ,209    ,202    ,39     ,61     ,138    ,5      ,52     ,149    ,96     ,33     ,       ,       ,       ,       ,
