
drop table if exists atn_acoustic_meta;
create table atn_acoustic_meta (
    acoustic_meta_id  serial,
    serialnum         text,
    tagfamily         text,
    eventid           integer,
    tagcode           text,
    ptt               integer,
    toppid            integer,
    taggingdate       text,
    animal_id         integer,
    len1              text,
    len1type          text,
    len2              text,
    len2type          text,
    len3              text,
    len3type          text,
    mass              text,
    masstype          text,
    sex               text,
    species           text,
    commonname        text,
    dlatdd            double precision,
    dlondd            double precision,
    seriesname        text,
    idcode1           integer,
    codespace1        text,
    sensor1           text,
    slope1            real,
    intercept1        real,
    idcode2           integer,
    codespace2        text,
    sensor2           text,
    slope2            real,
    intercept2        real,
    idcode3           integer,
    codespace3        text,
    sensor3           text,
    slope3            real,
    intercept3        real,
    vr4_feed          text
);

